version: '3'
services: 
    caddy:
      image: alpine-caddy
      container_name: alpine-caddy
      restart: always
      ports: 
       - "80:80"
       - "443:443"
       - "2015:2015"
      volumes: 
       - .:/etc/caddy/
      command: caddy -conf /etc/caddy/Caddyfile